name: BinaryCore
version: 2.1.0
author: BinaryOverload
main: es.esy.williamoldham.binarycore.BinaryCore
commands:
  binary-info:
    description: Shows all of my plugins
  update:
    description: Tries to update the plugins