name: BinaryCore
version: 2.0.1
author: BinaryOverload
main: es.esy.williamoldham.binarycore.BinaryCore
commands:
  binary-info:
    description: Shows all of my plugins
  update:
    description: Tries to update the plugins